[package]
edition = "2021"
name = "rust-dice"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lambda_http = "0.8.0"
rand = {version="0.8.5", features=["small_rng"]}
tokio = "1"
tracing-subscriber = "0.3.17"